# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'LinuxSniffyScout.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFormLayout, QGridLayout,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSplitter, QStatusBar,
    QTabWidget, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1328, 725)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 220, 1321, 481))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 60, 411, 121))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.layoutWidget = QWidget(self.tab)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 0, 401, 91))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_env = QPushButton(self.layoutWidget)
        self.pushButton_env.setObjectName(u"pushButton_env")
        font = QFont()
        font.setPointSize(8)
        self.pushButton_env.setFont(font)

        self.gridLayout.addWidget(self.pushButton_env, 0, 1, 1, 1)

        self.pushButton_SUID = QPushButton(self.layoutWidget)
        self.pushButton_SUID.setObjectName(u"pushButton_SUID")

        self.gridLayout.addWidget(self.pushButton_SUID, 2, 0, 1, 1)

        self.pushButton_pwdandshadow = QPushButton(self.layoutWidget)
        self.pushButton_pwdandshadow.setObjectName(u"pushButton_pwdandshadow")

        self.gridLayout.addWidget(self.pushButton_pwdandshadow, 1, 0, 1, 1)

        self.pushButton_pstree = QPushButton(self.layoutWidget)
        self.pushButton_pstree.setObjectName(u"pushButton_pstree")
        self.pushButton_pstree.setFont(font)

        self.gridLayout.addWidget(self.pushButton_pstree, 2, 1, 1, 1)

        self.pushButton_cron = QPushButton(self.layoutWidget)
        self.pushButton_cron.setObjectName(u"pushButton_cron")

        self.gridLayout.addWidget(self.pushButton_cron, 0, 0, 1, 1)

        self.pushButton_systemctl_status = QPushButton(self.layoutWidget)
        self.pushButton_systemctl_status.setObjectName(u"pushButton_systemctl_status")
        self.pushButton_systemctl_status.setFont(font)

        self.gridLayout.addWidget(self.pushButton_systemctl_status, 1, 3, 1, 1)

        self.pushButton_findhide = QPushButton(self.layoutWidget)
        self.pushButton_findhide.setObjectName(u"pushButton_findhide")
        self.pushButton_findhide.setFont(font)

        self.gridLayout.addWidget(self.pushButton_findhide, 0, 2, 1, 1)

        self.pushButton_hosts = QPushButton(self.layoutWidget)
        self.pushButton_hosts.setObjectName(u"pushButton_hosts")
        self.pushButton_hosts.setFont(font)

        self.gridLayout.addWidget(self.pushButton_hosts, 1, 2, 1, 1)

        self.pushButton_kernel = QPushButton(self.layoutWidget)
        self.pushButton_kernel.setObjectName(u"pushButton_kernel")
        self.pushButton_kernel.setFont(font)

        self.gridLayout.addWidget(self.pushButton_kernel, 2, 3, 1, 1)

        self.pushButton_rookit = QPushButton(self.layoutWidget)
        self.pushButton_rookit.setObjectName(u"pushButton_rookit")
        self.pushButton_rookit.setFont(font)

        self.gridLayout.addWidget(self.pushButton_rookit, 1, 1, 1, 1)

        self.pushButton_lsattr = QPushButton(self.layoutWidget)
        self.pushButton_lsattr.setObjectName(u"pushButton_lsattr")
        self.pushButton_lsattr.setFont(font)

        self.gridLayout.addWidget(self.pushButton_lsattr, 0, 3, 1, 1)

        self.pushButton_bashrc = QPushButton(self.layoutWidget)
        self.pushButton_bashrc.setObjectName(u"pushButton_bashrc")
        self.pushButton_bashrc.setFont(font)

        self.gridLayout.addWidget(self.pushButton_bashrc, 2, 2, 1, 1)

        self.pushButton_init1 = QPushButton(self.layoutWidget)
        self.pushButton_init1.setObjectName(u"pushButton_init1")
        self.pushButton_init1.setFont(font)

        self.gridLayout.addWidget(self.pushButton_init1, 0, 4, 1, 1)

        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.layoutWidget1 = QWidget(self.tab_5)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(0, 0, 361, 91))
        self.gridLayout_2 = QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.comboBox_dockerlist = QComboBox(self.layoutWidget1)
        self.comboBox_dockerlist.setObjectName(u"comboBox_dockerlist")

        self.gridLayout_2.addWidget(self.comboBox_dockerlist, 0, 0, 1, 2)

        self.pushButton_dockerlist = QPushButton(self.layoutWidget1)
        self.pushButton_dockerlist.setObjectName(u"pushButton_dockerlist")
        self.pushButton_dockerlist.setFont(font)

        self.gridLayout_2.addWidget(self.pushButton_dockerlist, 0, 2, 1, 1)

        self.pushButton_dockerlogs = QPushButton(self.layoutWidget1)
        self.pushButton_dockerlogs.setObjectName(u"pushButton_dockerlogs")
        self.pushButton_dockerlogs.setFont(font)

        self.gridLayout_2.addWidget(self.pushButton_dockerlogs, 1, 0, 1, 1)

        self.pushButton_dockerimages = QPushButton(self.layoutWidget1)
        self.pushButton_dockerimages.setObjectName(u"pushButton_dockerimages")
        self.pushButton_dockerimages.setFont(font)

        self.gridLayout_2.addWidget(self.pushButton_dockerimages, 1, 1, 1, 1)

        self.pushButton_dockercopyfile = QPushButton(self.layoutWidget1)
        self.pushButton_dockercopyfile.setObjectName(u"pushButton_dockercopyfile")
        self.pushButton_dockercopyfile.setFont(font)

        self.gridLayout_2.addWidget(self.pushButton_dockercopyfile, 1, 2, 1, 1)

        self.pushButton_copyfile2docker = QPushButton(self.layoutWidget1)
        self.pushButton_copyfile2docker.setObjectName(u"pushButton_copyfile2docker")
        self.pushButton_copyfile2docker.setFont(font)

        self.gridLayout_2.addWidget(self.pushButton_copyfile2docker, 2, 2, 1, 1)

        self.pushButton_restartdocker = QPushButton(self.layoutWidget1)
        self.pushButton_restartdocker.setObjectName(u"pushButton_restartdocker")
        self.pushButton_restartdocker.setFont(font)

        self.gridLayout_2.addWidget(self.pushButton_restartdocker, 2, 0, 1, 1)

        self.pushButton_dockernetwork = QPushButton(self.layoutWidget1)
        self.pushButton_dockernetwork.setObjectName(u"pushButton_dockernetwork")
        self.pushButton_dockernetwork.setFont(font)

        self.gridLayout_2.addWidget(self.pushButton_dockernetwork, 2, 1, 1, 1)

        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.pushButton_chattr = QPushButton(self.tab_4)
        self.pushButton_chattr.setObjectName(u"pushButton_chattr")
        self.pushButton_chattr.setGeometry(QRect(0, 0, 101, 23))
        self.pushButton_chattr.setFont(font)
        self.pushButton_userdel = QPushButton(self.tab_4)
        self.pushButton_userdel.setObjectName(u"pushButton_userdel")
        self.pushButton_userdel.setGeometry(QRect(100, 0, 91, 23))
        self.pushButton_delfile = QPushButton(self.tab_4)
        self.pushButton_delfile.setObjectName(u"pushButton_delfile")
        self.pushButton_delfile.setGeometry(QRect(190, 0, 91, 23))
        self.pushButton_catfile = QPushButton(self.tab_4)
        self.pushButton_catfile.setObjectName(u"pushButton_catfile")
        self.pushButton_catfile.setGeometry(QRect(200, 70, 75, 23))
        self.pushButton_savefile = QPushButton(self.tab_4)
        self.pushButton_savefile.setObjectName(u"pushButton_savefile")
        self.pushButton_savefile.setGeometry(QRect(280, 70, 75, 23))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_restartapache2 = QPushButton(self.tab_2)
        self.pushButton_restartapache2.setObjectName(u"pushButton_restartapache2")
        self.pushButton_restartapache2.setGeometry(QRect(20, 10, 111, 23))
        self.pushButton_quick_open_apache_proxy = QPushButton(self.tab_2)
        self.pushButton_quick_open_apache_proxy.setObjectName(u"pushButton_quick_open_apache_proxy")
        self.pushButton_quick_open_apache_proxy.setGeometry(QRect(140, 10, 121, 23))
        self.pushButton_quick_open_apache_proxy.setFont(font)
        self.pushButton_updateaudidt = QPushButton(self.tab_2)
        self.pushButton_updateaudidt.setObjectName(u"pushButton_updateaudidt")
        self.pushButton_updateaudidt.setGeometry(QRect(20, 40, 71, 23))
        self.pushButton_updateaudidt.setFont(font)
        self.pushButton_restartaudit = QPushButton(self.tab_2)
        self.pushButton_restartaudit.setObjectName(u"pushButton_restartaudit")
        self.pushButton_restartaudit.setGeometry(QRect(90, 40, 111, 23))
        self.tabWidget.addTab(self.tab_2, "")
        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(425, 10, 501, 171))
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.textEdit_1 = QTextEdit(self.tab_6)
        self.textEdit_1.setObjectName(u"textEdit_1")
        self.textEdit_1.setGeometry(QRect(0, 0, 491, 141))
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.textEdit_2 = QTextEdit(self.tab_7)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(0, 0, 491, 141))
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.textEdit_3 = QTextEdit(self.tab_8)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(0, 0, 461, 141))
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.textEdit_4 = QTextEdit(self.tab_9)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.textEdit_4.setGeometry(QRect(0, 0, 491, 141))
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.textEdit_5 = QTextEdit(self.tab_11)
        self.textEdit_5.setObjectName(u"textEdit_5")
        self.textEdit_5.setGeometry(QRect(0, 0, 491, 141))
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.textEdit_6 = QTextEdit(self.tab_12)
        self.textEdit_6.setObjectName(u"textEdit_6")
        self.textEdit_6.setGeometry(QRect(0, 0, 491, 141))
        self.tabWidget_2.addTab(self.tab_12, "")
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.textEdit_7 = QTextEdit(self.tab_13)
        self.textEdit_7.setObjectName(u"textEdit_7")
        self.textEdit_7.setGeometry(QRect(0, 0, 501, 141))
        self.tabWidget_2.addTab(self.tab_13, "")
        self.tab_15 = QWidget()
        self.tab_15.setObjectName(u"tab_15")
        self.textEdit_8 = QTextEdit(self.tab_15)
        self.textEdit_8.setObjectName(u"textEdit_8")
        self.textEdit_8.setGeometry(QRect(0, 0, 491, 141))
        self.tabWidget_2.addTab(self.tab_15, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.textEdit_9 = QTextEdit(self.tab_10)
        self.textEdit_9.setObjectName(u"textEdit_9")
        self.textEdit_9.setGeometry(QRect(0, 0, 491, 141))
        self.tabWidget_2.addTab(self.tab_10, "")
        self.layoutWidget2 = QWidget(self.centralwidget)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 190, 861, 25))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_findstr = QPushButton(self.layoutWidget2)
        self.pushButton_findstr.setObjectName(u"pushButton_findstr")

        self.horizontalLayout.addWidget(self.pushButton_findstr)

        self.lineEdit_findstr = QLineEdit(self.layoutWidget2)
        self.lineEdit_findstr.setObjectName(u"lineEdit_findstr")

        self.horizontalLayout.addWidget(self.lineEdit_findstr)

        self.pushButton_cmd = QPushButton(self.layoutWidget2)
        self.pushButton_cmd.setObjectName(u"pushButton_cmd")

        self.horizontalLayout.addWidget(self.pushButton_cmd)

        self.pushButton_dockerexec = QPushButton(self.layoutWidget2)
        self.pushButton_dockerexec.setObjectName(u"pushButton_dockerexec")

        self.horizontalLayout.addWidget(self.pushButton_dockerexec)

        self.pushButton_savenote = QPushButton(self.layoutWidget2)
        self.pushButton_savenote.setObjectName(u"pushButton_savenote")

        self.horizontalLayout.addWidget(self.pushButton_savenote)

        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(300, 0, 80, 80))
        self.label_3.setPixmap(QPixmap(u"Designer.png"))
        self.label_3.setScaledContents(True)
        self.layoutWidget3 = QWidget(self.centralwidget)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(10, 7, 281, 54))
        self.formLayout = QFormLayout(self.layoutWidget3)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.label = QLabel(self.layoutWidget3)
        self.label.setObjectName(u"label")

        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)

        self.lineEdit_ipandport = QLineEdit(self.layoutWidget3)
        self.lineEdit_ipandport.setObjectName(u"lineEdit_ipandport")

        self.gridLayout_3.addWidget(self.lineEdit_ipandport, 0, 1, 1, 1)

        self.pushButton_login = QPushButton(self.layoutWidget3)
        self.pushButton_login.setObjectName(u"pushButton_login")

        self.gridLayout_3.addWidget(self.pushButton_login, 0, 2, 1, 1)


        self.formLayout.setLayout(0, QFormLayout.LabelRole, self.gridLayout_3)

        self.splitter_2 = QSplitter(self.layoutWidget3)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.label_2 = QLabel(self.splitter_2)
        self.label_2.setObjectName(u"label_2")
        self.splitter_2.addWidget(self.label_2)
        self.lineEdit_usernameandpasswd = QLineEdit(self.splitter_2)
        self.lineEdit_usernameandpasswd.setObjectName(u"lineEdit_usernameandpasswd")
        self.splitter_2.addWidget(self.lineEdit_usernameandpasswd)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.splitter_2)

        self.tabWidget_3 = QTabWidget(self.centralwidget)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(930, 10, 401, 171))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.pushButton_logindefs = QPushButton(self.tab_3)
        self.pushButton_logindefs.setObjectName(u"pushButton_logindefs")
        self.pushButton_logindefs.setGeometry(QRect(10, 10, 111, 23))
        self.pushButton_crontab = QPushButton(self.tab_3)
        self.pushButton_crontab.setObjectName(u"pushButton_crontab")
        self.pushButton_crontab.setGeometry(QRect(10, 40, 111, 23))
        self.pushButton_profile = QPushButton(self.tab_3)
        self.pushButton_profile.setObjectName(u"pushButton_profile")
        self.pushButton_profile.setGeometry(QRect(10, 70, 111, 23))
        self.pushButton_rclocal = QPushButton(self.tab_3)
        self.pushButton_rclocal.setObjectName(u"pushButton_rclocal")
        self.pushButton_rclocal.setGeometry(QRect(10, 100, 111, 23))
        self.pushButton_etcinitdmysql = QPushButton(self.tab_3)
        self.pushButton_etcinitdmysql.setObjectName(u"pushButton_etcinitdmysql")
        self.pushButton_etcinitdmysql.setGeometry(QRect(130, 10, 111, 23))
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_14 = QWidget()
        self.tab_14.setObjectName(u"tab_14")
        self.pushButton_mycnf = QPushButton(self.tab_14)
        self.pushButton_mycnf.setObjectName(u"pushButton_mycnf")
        self.pushButton_mycnf.setGeometry(QRect(10, 10, 111, 23))
        self.pushButton_httpd = QPushButton(self.tab_14)
        self.pushButton_httpd.setObjectName(u"pushButton_httpd")
        self.pushButton_httpd.setGeometry(QRect(10, 40, 111, 23))
        self.tabWidget_3.addTab(self.tab_14, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"LinuxSniffyScount Beta v0.2 - CreatedBy : Tokeii", None))
        self.textEdit.setMarkdown("")
#if QT_CONFIG(tooltip)
        self.pushButton_env.setToolTip(QCoreApplication.translate("MainWindow", u"\u65e0\u6cd5\u6b63\u5e38\u6253\u5370\uff0c\u9700\u8981\u624b\u52a8\u6267\u884c", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_env.setText(QCoreApplication.translate("MainWindow", u"\u73af\u5883\u53d8\u91cf(set)", None))
#if QT_CONFIG(tooltip)
        self.pushButton_SUID.setToolTip(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5\u91cd\u8981\u6587\u4ef6\u662f\u5426\u5b58\u5728suid\u548csgid\u6743\u9650", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_SUID.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5SUID", None))
#if QT_CONFIG(tooltip)
        self.pushButton_pwdandshadow.setToolTip(QCoreApplication.translate("MainWindow", u"\u8bfb\u53d6/etc/passwd\uff0c\u4ee5\u53ca/etc/shadow\u6587\u4ef6\uff0cpasswd\u6587\u4ef6\u53ea\u8bfb\u53d6\u80fd\u767b\u5f55\u7684\u7528\u6237", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_pwdandshadow.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5\u7528\u6237", None))
#if QT_CONFIG(tooltip)
        self.pushButton_pstree.setToolTip(QCoreApplication.translate("MainWindow", u"ps -aux", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_pstree.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5\u8fdb\u7a0b", None))
#if QT_CONFIG(tooltip)
        self.pushButton_cron.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5370\u51fa\u673a\u5668\u4e2d\u7684\u6240\u6709\u5b9a\u65f6\u4efb\u52a1", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_cron.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pushButton_cron.setText(QCoreApplication.translate("MainWindow", u"\u5b9a\u65f6\u4efb\u52a1", None))
#if QT_CONFIG(tooltip)
        self.pushButton_systemctl_status.setToolTip(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u5f00\u673a\u7684\u6240\u6709\u670d\u52a1", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_systemctl_status.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u6240\u6709\u670d\u52a1", None))
#if QT_CONFIG(tooltip)
        self.pushButton_findhide.setToolTip(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u6240\u6709\u7684.*\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_findhide.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u9690\u85cf\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.pushButton_hosts.setToolTip(QCoreApplication.translate("MainWindow", u"/etc/hosts", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_hosts.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770bhosts", None))
#if QT_CONFIG(tooltip)
        self.pushButton_kernel.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bf9\u67e5\u627e\u6076\u610f\u9a71\u52a8\u6709\u5e2e\u52a9", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_kernel.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u6838\u5fc3\u65e5\u5fd7", None))
#if QT_CONFIG(tooltip)
        self.pushButton_rookit.setToolTip(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u5e38\u89c1\u76ee\u5f55\u4e0b\u7684*.ko\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_rookit.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627erookit", None))
#if QT_CONFIG(tooltip)
        self.pushButton_lsattr.setToolTip(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u5e38\u89c1\u76ee\u5f55\u4e0b\u7684ia\u7279\u6b8a\u5c5e\u6027\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_lsattr.setText(QCoreApplication.translate("MainWindow", u"\u7279\u6b8a\u5c5e\u6027\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.pushButton_bashrc.setToolTip(QCoreApplication.translate("MainWindow", u"\u6267\u884c\u6253\u5370\u547d\u4ee4\uff1a'cat ~/.bashrc', 'cat ~/.profile', 'cat /etc/profile'", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_bashrc.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770bbashrc", None))
#if QT_CONFIG(tooltip)
        self.pushButton_init1.setToolTip(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u5e38\u89c1\u76ee\u5f55\u4e0b\u7684ia\u7279\u6b8a\u5c5e\u6027\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_init1.setText(QCoreApplication.translate("MainWindow", u"\u7236\u8fdb\u7a0b\u4e3a1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u68c0\u67e5", None))
#if QT_CONFIG(tooltip)
        self.pushButton_dockerlist.setToolTip(QCoreApplication.translate("MainWindow", u"\u8bfb\u53d6\u6b63\u5728\u8fd0\u884c\u7684docker\u5bb9\u5668", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_dockerlist.setText(QCoreApplication.translate("MainWindow", u"\u5237\u65b0docker\u5217\u8868", None))
#if QT_CONFIG(tooltip)
        self.pushButton_dockerlogs.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5370docker\u65e5\u5fd7", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_dockerlogs.setText(QCoreApplication.translate("MainWindow", u"docker\u5bb9\u5668\u65e5\u5fd7", None))
#if QT_CONFIG(tooltip)
        self.pushButton_dockerimages.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5370\u4e3b\u673a\u7a7a\u95f4\u5185\u7684docker\u955c\u50cf", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_dockerimages.setText(QCoreApplication.translate("MainWindow", u"docker\u955c\u50cf\u5217\u8868", None))
#if QT_CONFIG(tooltip)
        self.pushButton_dockercopyfile.setToolTip(QCoreApplication.translate("MainWindow", u"\u4ece\u5bb9\u5668\u5185\u590d\u5236\u5230\u4e3b\u673a\u4e2d\uff0c\u9ed8\u8ba4\u590d\u5236\u5230/tmp/..\uff0c\u4e0b\u9762\u8f93\u5165\u6846\u5929\u4e0bdocker\u5bb9\u5668\u7684\u6587\u4ef6\u4f4d\u7f6e", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_dockercopyfile.setText(QCoreApplication.translate("MainWindow", u"docker\u5185\u590d\u5236\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.pushButton_copyfile2docker.setToolTip(QCoreApplication.translate("MainWindow", u"\u4ece\u5bb9\u5668\u5185\u590d\u5236\u5230\u4e3b\u673a\u4e2d\uff0c\u9ed8\u8ba4\u4ece/tmp/..\u590d\u5236\uff0c\u4e0b\u9762\u8f93\u5165\u6846\u5929\u4e0bdocker\u5bb9\u5668\u7684\u6587\u4ef6\u4f4d\u7f6e", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_copyfile2docker.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5236\u6587\u4ef6\u81f3docker\u5185", None))
#if QT_CONFIG(tooltip)
        self.pushButton_restartdocker.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5370docker\u65e5\u5fd7", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_restartdocker.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u542fdocker\u5bb9\u5668", None))
#if QT_CONFIG(tooltip)
        self.pushButton_dockernetwork.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5370\u4e3b\u673a\u7a7a\u95f4\u5185\u7684docker\u955c\u50cf", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_dockernetwork.setText(QCoreApplication.translate("MainWindow", u"docker\u7f51\u5361\u5217\u8868", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"docker\u64cd\u4f5c", None))
#if QT_CONFIG(tooltip)
        self.pushButton_chattr.setToolTip(QCoreApplication.translate("MainWindow", u"\u53d6\u6d88\u6587\u4ef6\u7684ia\u5c5e\u6027", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_chattr.setText(QCoreApplication.translate("MainWindow", u"\u53d6\u6d88\u6587\u4ef6\u7279\u6b8a\u5c5e\u6027", None))
#if QT_CONFIG(tooltip)
        self.pushButton_userdel.setToolTip(QCoreApplication.translate("MainWindow", u"\u5f3a\u5236\u5220\u9664\u7528\u6237 userdel -rf username \u4e0b\u9762\u8f93\u5165\u586b\u5199\u7528\u6237\u540d", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_userdel.setText(QCoreApplication.translate("MainWindow", u"\u5f3a\u5236\u5220\u9664\u7528\u6237", None))
#if QT_CONFIG(tooltip)
        self.pushButton_delfile.setToolTip(QCoreApplication.translate("MainWindow", u"\u5f3a\u5236\u5220\u9664\u6587\u4ef6\u6216\u6587\u4ef6\u5939\uff0c\u6267\u884crm -rf .... \uff08\u8c28\u614e\u4f7f\u7528\uff09", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_delfile.setText(QCoreApplication.translate("MainWindow", u"\u5f3a\u5236\u5220\u9664\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.pushButton_catfile.setToolTip(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91\u8f93\u5165\u6846\u8f93\u5165\u7edd\u5bf9\u8def\u5f84\u7684\u6587\u4ef6\uff0c\u4f7f\u7528\u53f3\u4fa7\u7684\u4fdd\u5b58\u6587\u4ef6\u4fdd\u5b58", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_catfile.setText(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.pushButton_savefile.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6587\u4ef6\uff0c\u4fdd\u5b58\u5230\u8f93\u5165\u6846\u7684\u7edd\u5bf9\u8def\u5f84\uff0c\u4f7f\u7528base64 -d\u4fdd\u5b58", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_savefile.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6587\u4ef6", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u64cd\u4f5c\u6587\u4ef6", None))
        self.pushButton_restartapache2.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u901f\u91cd\u542fApache2", None))
        self.pushButton_quick_open_apache_proxy.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u901f\u5f00\u542fApache\u53cd\u4ee3", None))
        self.pushButton_updateaudidt.setText(QCoreApplication.translate("MainWindow", u"\u4e0a\u4f20Auditd", None))
        self.pushButton_restartaudit.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u901f\u91cd\u542fAudit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u5feb\u901f\u6267\u884c", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb01", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb02", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb03", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb04", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb05", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb06", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb07", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_15), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb08", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"\u7b14\u8bb09", None))
        self.pushButton_findstr.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e", None))
        self.pushButton_cmd.setText(QCoreApplication.translate("MainWindow", u"\u6267\u884c", None))
        self.pushButton_dockerexec.setText(QCoreApplication.translate("MainWindow", u"\u6267\u884cdocker\u5185\u547d\u4ee4", None))
        self.pushButton_savenote.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u5168\u90e8\u7b14\u8bb0", None))
        self.label_3.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"IP:Port", None))
        self.lineEdit_ipandport.setInputMask("")
        self.lineEdit_ipandport.setText("")
        self.pushButton_login.setText(QCoreApplication.translate("MainWindow", u"\u767b\u5f55", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"User:Pwd", None))
        self.lineEdit_usernameandpasswd.setInputMask("")
        self.lineEdit_usernameandpasswd.setText("")
#if QT_CONFIG(tooltip)
        self.tabWidget_3.setToolTip(QCoreApplication.translate("MainWindow", u"\u53ef\u9002\u7528\u4e8e\u64cd\u4f5c\u6587\u4ef6\u4e2d\u7684\u4fdd\u5b58", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_logindefs.setText(QCoreApplication.translate("MainWindow", u"/etc/login.defs", None))
        self.pushButton_crontab.setText(QCoreApplication.translate("MainWindow", u"/etc/crontab", None))
        self.pushButton_profile.setText(QCoreApplication.translate("MainWindow", u"/etc/profile", None))
        self.pushButton_rclocal.setText(QCoreApplication.translate("MainWindow", u"/etc/rc.local", None))
        self.pushButton_etcinitdmysql.setText(QCoreApplication.translate("MainWindow", u"/etc/init.d/mysql", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u5feb\u901f\u6253\u5f00", None))
        self.pushButton_mycnf.setText(QCoreApplication.translate("MainWindow", u"/etc/my.cnf", None))
        self.pushButton_httpd.setText(QCoreApplication.translate("MainWindow", u"httpd.conf", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), QCoreApplication.translate("MainWindow", u"\u4e2d\u95f4\u4ef6\u6216\u6570\u636e\u5e93\u7b49\u5feb\u901f\u6253\u5f00", None))
    # retranslateUi

